feat: adding static-node parameter to bee chart
ethersphere/helm pull request #156
Opened 2021-09-23 10:12 UTC by notanatol

2021-09-23 10:51 UTC, acud requested changes
need to increment the chart version

2021-09-23 11:09 UTC, aleksandarknezevic approved these changes

2021-09-23 11:32 UTC, vandot commented on charts/bee/values.yaml
> +  static-nodes: ""
You should use `_` here, please place it alphabetically in the list

2021-09-28 09:32 UTC, acud approved these changes

2021-09-28 09:47 UTC, merged